title: Empowering People Scotland
description: Specialist services designed to empower individuals with extra support needs and hidden disabilities, to gain willful employment and lead fulfilling lives.
url: https://empowering-people.co.uk
baseurl: ""

permalink: pretty

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
