services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --drafts
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle

volumes:
  jekyll_bundle:
